# Generated by Django 4.1.13 on 2024-10-30 14:12

import Api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDeReclamaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_type', djongo.models.fields.EmbeddedField(model_container=Api.models.IdType)),
                ('department', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_photo_url', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('users', djongo.models.fields.EmbeddedField(model_container=Api.models.User)),
                ('comments', djongo.models.fields.ArrayField(model_container=Api.models.Comment)),
            ],
        ),
        migrations.CreateModel(
            name='Resennia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('users', djongo.models.fields.ArrayField(model_container=Api.models.User)),
            ],
        ),
    ]
